services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

